# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [1]:
import random

import numpy as np
import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [5]:
arr1 = [0 for i in range(1000)]
print(arr1)
sys.getsizeof(arr1)


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

8856

In [6]:
arr2 = np.zeros(1000, dtype=np.int8)
print(sys.getsizeof(arr2))


1112


## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [4]:
arr = np.array([1.2, 5.6, 9.9, .5, 0.4])
arr[[0, 2, -1]]

array([1.2, 9.9, 0.4])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [5]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
np.sum(array[[0, 4, 5, -1]], dtype=int)

np.int64(27)

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [9]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [10]:
mean_axis_x = np.mean(A, axis=0)
mean_axis_x

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [11]:
stddev = np.std(A, axis=1)
stddev

array([2.5, 3. , 4. , 3.5, 3. ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [80]:
sum_axis_y = np.sum(A, axis=0)
sum_axis_y[1]

np.int64(42)

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [11]:
np.array(A[[0, 1]])

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [12]:
np.array(A[[0, 2, -1]])

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [86]:
import time
start = time.time()
[i for i in range(1000000)]
end = time.time()
time_result = end - start
time_result

0.09700131416320801

In [88]:
%timeit np.arange(1000000)


The slowest run took 4.25 times longer than the fastest. This could mean that an intermediate result is being cached.
4.4 ms ± 2.95 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Task 6.2

In [ ]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%time unknown_signature(vector1, vector2)
result

In [102]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

%timeit np.dot(vector1, vector2)
np.dot(vector1, vector2)

The slowest run took 4.48 times longer than the fastest. This could mean that an intermediate result is being cached.
3.22 μs ± 1.73 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


np.int64(32)

### Task 6.3

In [26]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

In [104]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
np.multiply(matrix1, matrix2)

array([[ 5, 12],
       [21, 32]])

### Task 6.4

In [106]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]
unknown_signature(lst)

3.0

In [108]:
lst = np.array([1, 2, 3, 4, 5])
lst.mean()

np.float64(3.0)

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [31]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [113]:
lst = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, True])
new_value = 0

lst[mask] = new_value
print(lst)

[0 2 0 4 0]


### Task 7.2

In [118]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [129]:
list1 = np.array([5, 2, 7, 4, 9], dtype=np.int32)
list2 = np.array([3, 6, 1, 8, 10], dtype=np.int32)

print(np.bitwise_not(list1))
print(np.bitwise_and(list1, list2))
print(np.bitwise_or(list1, list2))

[ -6  -3  -8  -5 -10]
[1 2 1 0 8]
[ 7  6  7 12 11]


### Task 7.3 Optional

In [133]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [143]:
my_list = np.array([6, 9, 12, 14, 17, 20])
arr = np.array(my_list)
mask = (arr % 2 == 0) & ((arr % 3 == 0) | (arr > 10))
result = (arr[mask] ^ 7) + 2
result.tolist()

[3, 13, 11, 21]